# Generated by Django 3.1.7 on 2021-03-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='is_favourited',
            new_name='is_favourite',
        ),
    ]
